<a href="https://colab.research.google.com/github/felixabel684/Latihan-Tugas-Data-Mining/blob/main/Preprocessing_Data_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
dataset = pd.read_csv('Data2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [41]:
print(x)

[['Brazil' 44.0 72000.0]
 ['Sweden' 27.0 48000.0]
 ['Germany' 33.0 54000.0]
 ['Spain' nan 61000.0]
 ['China' 40.0 81000.0]
 ['France' 35.0 58000.0]
 ['Japan' 28.0 52000.0]
 ['Germany' 48.0 nan]
 ['Japan' 51.0 83000.0]
 ['Germany' 37.0 62000.0]]


In [42]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes']


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [44]:
print(x)

[['Brazil' 44.0 72000.0]
 ['Sweden' 27.0 48000.0]
 ['Germany' 33.0 54000.0]
 ['Spain' 38.111111111111114 61000.0]
 ['China' 40.0 81000.0]
 ['France' 35.0 58000.0]
 ['Japan' 28.0 52000.0]
 ['Germany' 48.0 63444.444444444445]
 ['Japan' 51.0 83000.0]
 ['Germany' 37.0 62000.0]]


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [47]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 33.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.111111111111114 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 40.0 81000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 28.0 52000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 48.0 63444.444444444445]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 51.0 83000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 37.0 62000.0]]


In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [49]:
print(y)

[0 1 0 0 1 0 1 1 0 1]


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [52]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 28.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 40.0 81000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.111111111111114 61000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 48.0 63444.444444444445]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 51.0 83000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [53]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 33.0 54000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 37.0 62000.0]]


In [54]:
print(y_train)

[1 1 0 0 1 1 0 0]


In [55]:
print(y_test)

[0 1]


In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [60]:
print(x_train)

[[0.0 0.0 0.0 -0.3779644730092272 1.7320508075688774 -0.3779644730092272
  -0.3779644730092272 -1.3344144438112333 -1.066150329833471]
 [0.0 1.0 0.0 -0.3779644730092272 -0.5773502691896258 -0.3779644730092272
  -0.3779644730092272 0.136164739164412 1.3482985733035002]
 [1.0 0.0 0.0 -0.3779644730092272 -0.5773502691896258 -0.3779644730092272
  -0.3779644730092272 0.6263578001562937 0.5989868447437505]
 [0.0 0.0 0.0 -0.3779644730092272 -0.5773502691896258 2.6457513110645903
  -0.3779644730092272 -0.09531531741508734 -0.3168386012737212]
 [0.0 0.0 0.0 -0.3779644730092272 -0.5773502691896258 -0.3779644730092272
  2.6457513110645903 -1.4569627090592037 -1.3991777647489152]
 [0.0 0.0 0.0 2.6457513110645903 -0.5773502691896258 -0.3779644730092272
  -0.3779644730092272 1.1165508611481754 -0.11332183549206076]
 [0.0 0.0 0.0 -0.3779644730092272 1.7320508075688774 -0.3779644730092272
  -0.3779644730092272 1.4841956568920869 1.5148122907612223]
 [0.0 0.0 1.0 -0.3779644730092272 -0.5773502691896258

In [61]:
print(x_test)

[[0.0 0.0 0.0 2.6457513110645903 -0.5773502691896258 -0.3779644730092272
  -0.3779644730092272 -0.7216731175713811 -0.8996366123757487]
 [0.0 0.0 0.0 2.6457513110645903 -0.5773502691896258 -0.3779644730092272
  -0.3779644730092272 -0.23148005657949933 -0.23358174254486014]]
